### ISSUE TITLE
Outline specific remote experiments and an API reference for clients

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-webapp#6]
All clients web, Android etc. should be able to access remote experiment features. Please outline experiments and describe what APIs/features are required.

**Comment by jithinbp** [comment]
Using flasgger. Flask+Swagger. API reference can be accessed at <base url>/apidocs/

---

![psl_flasgger](https://user-images.githubusercontent.com/6078658/29911752-aa8349ba-8e4c-11e7-880b-a467f3971f5d.png)
![psl_virt_apidocs](https://user-images.githubusercontent.com/6078658/29911751-aa82b95a-8e4c-11e7-8043-705cf1c8f7da.png)
