### ISSUE TITLE
Social media clickable link on photo

### ISSUE THREAD

**Issue by imrrahul** [fossasia/pslab-webapp#96]
**Actual Behaviour**

There should be a clickable link on photo of team members so that visitors and interact with the members directly and can get a wide idea regarding the respective project.

**Expected Behaviour**

Social media link should be provided on photo which should appear after hover.

**Screenshots of the issue**

![screenshot from 2019-02-16 02-35-33](https://user-images.githubusercontent.com/37583853/52884657-94083f00-3194-11e9-82b6-1272885dba7e.png)

**Would you like to work on the issue?**
yes

**Comment by mariobehling** [comment]
Not the right place. We are focusing on the actual software project. Please help and focus on the software or hardware only atm.

**Comment by imrrahul** [comment]
Thanks @mariobehling working on that....
